language: node_js
node_js:
 - 9
branch:
  only:
   - master

install:
  - npm install

script:
  - npm run build
  - npm run tslint

deploy:
  provider: npm
  email: tiguerin@microsoft.com
  api_key: "YOUR_AUTH_TOKEN"
